(* 目的: 月と日に応じて星座を返す。 *)
(* seiza : int -> int -> string *)
let seiza month data = if       month == 1  then if data >= 20 && data <= 31 then "水瓶"  else "山羊"
                       else if  month == 2  then if data >= 19 && data <= 30 then "魚"    else "水瓶"
                       else if  month == 3  then if data >= 21 && data <= 31 then "牡羊"  else "魚"
                       else if  month == 4  then if data >= 20 && data <= 30 then "牡牛"   else "牡羊"
                       else if  month == 5  then if data >= 21 && data <= 31 then "双子"  else "牡牛"
                       else if  month == 6  then if data >= 22 && data <= 30 then "蟹"    else "双子"
                       else if  month == 7  then if data >= 23 && data <= 31 then "獅子"  else "蟹"
                       else if  month == 8  then if data >= 23 && data <= 31 then "乙女"   else "獅子"
                       else if  month == 9  then if data >= 23 && data <= 30 then "天秤"  else "乙女"
                       else if  month == 10 then if data >= 24 && data <= 31 then "蠍"    else "天秤"
                       else if  month == 11 then if data >= 23 && data <= 30 then "射手" else "蠍"
                       else if  month == 12 then if data >= 22 && data <= 31 then "山羊"  else "射手"
                       else "INVALID MONTH"


(* テスト *)
let test1 = seiza 3 21 = "牡羊"
let test2 = seiza 4 19 = "牡羊"
let test3 = seiza 4 20 = "牡牛"
let test4 = seiza 5 20 = "牡牛"
let test5 = seiza 5 21 = "双子"
let test6 = seiza 6 21 = "双子"
let test7 = seiza 6 22 = "蟹"
let test8 = seiza 7 22 = "蟹"
let test9 = seiza 7 23 = "獅子"
let test10 = seiza 8 22 = "獅子"
let test11 = seiza 8 23 = "乙女"
let test12 = seiza 9 22 = "乙女"
let test13 = seiza 9 23 = "天秤"
let test14 = seiza 10 23 = "天秤"
let test15 = seiza 10 24 = "蠍"
let test16 = seiza 11 22 = "蠍"
let test17 = seiza 11 23 = "射手"
let test18 = seiza 12 21 = "射手"
let test19 = seiza 12 22 = "山羊"
let test20 = seiza 1 19 = "山羊"
let test21 = seiza 1 20 = "水瓶"
let test22 = seiza 2 18 = "水瓶"
let test23 = seiza 2 19 = "魚"
let test24 = seiza 3 20 = "魚"
